const AUTH_LOADING = "AUTH_LOADING";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAILED = "AUTH_FAILED";
const RESET_AUTH = "RESET_AUTH";
const LOGOUT = "LOGOUT";

const RESET_EMAIL_SENT = "RESET_EMAIL_SENT";
const RESET_EMAIL_SENDING_FAILED = "RESET_EMAIL_SENDING_FAILED";

const PASSWORD_CHANGED_SUCCESSFULLY = "PASSWORD_CHANGED_SUCCESSFULLY";
const PASSWORD_CHANGING_FAILED = "PASSWORD_CHANGING_FAILED";

export {
    RESET_AUTH,
    AUTH_LOADING,
    AUTH_SUCCESS,
    AUTH_FAILED,
    LOGOUT,

    RESET_EMAIL_SENT,
    RESET_EMAIL_SENDING_FAILED,

    PASSWORD_CHANGED_SUCCESSFULLY,
    PASSWORD_CHANGING_FAILED,
}