export const RESET_PROJECTS_ERRORS = "RESET_PROJECTS_ERRORS";

export const FETCHING_PROJECTS = "FETCHING_PROJECTS";
export const FETCHING_PROJECTS_SUCCESS = "FETCHING_PROJECTS_SUCCESS";
export const FETCHING_PROJECTS_FAILED = "FETCHING_PROJECTS_FAILED";

export const FETCHING_PROJECT = "FETCHING_PROJECT";
export const FETCHING_PROJECT_SUCCESS = "FETCHING_PROJECT_SUCCESS";
export const FETCHING_PROJECT_FAILED = "FETCHING_PROJECT_FAILED";

export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILED = "ADD_PROJECT_FAILED";

export const PROJECT_ACTIONS = "PROJECT_ACTIONS";
export const FINISH_PROJECT_SUCCESS = "FINISH_PROJECT_SUCCESS";
export const FINISH_PROJECT_FAILED = "FINISH_PROJECT_FAILED";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";

export const DASHBOARD_ACTION_SUCCESS = 'DASHBOARD_ACTION_SUCCESS';

export const DASHBOARD_PROJECTS_SUCCESS = 'DASHBOARD_PROJECTS_SUCCESS';
export const DASHBOARD_EMPLOYEES_SUCCESS = 'DASHBOARD_EMPLOYEES_SUCCESS';
export const DASHBOARD_CHARTS_SUCCESS = 'DASHBOARD_CHARTS_SUCCESS';
export const DASHBOARD_LATESTS_SUCCESS = 'DASHBOARD_LATESTS_SUCCESS';