const RESET_PROJECTS_ERRORS = "RESET_PROJECTS_ERRORS";

const FETCHING_PROJECTS = "FETCHING_PROJECTS";
const FETCHING_PROJECTS_SUCCESS = "FETCHING_PROJECTS_SUCCESS";
const FETCHING_PROJECTS_FAILED = "FETCHING_PROJECTS_FAILED";

const FETCHING_PROJECT = "FETCHING_PROJECT";
const FETCHING_PROJECT_SUCCESS = "FETCHING_PROJECT_SUCCESS";
const FETCHING_PROJECT_FAILED = "FETCHING_PROJECT_FAILED";

const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
const ADD_PROJECT_FAILED = "ADD_PROJECT_FAILED";

const PROJECT_ACTIONS = "PROJECT_ACTIONS";
const FINISH_PROJECT_SUCCESS = "FINISH_PROJECT_SUCCESS";
const FINISH_PROJECT_FAILED = "FINISH_PROJECT_FAILED";

const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";

export {
    RESET_PROJECTS_ERRORS,
    
    FETCHING_PROJECTS,
    FETCHING_PROJECTS_SUCCESS,
    FETCHING_PROJECTS_FAILED,

    FETCHING_PROJECT,
    FETCHING_PROJECT_SUCCESS,
    FETCHING_PROJECT_FAILED,

    ADD_PROJECT_SUCCESS,
    ADD_PROJECT_FAILED,

    PROJECT_ACTIONS,
    FINISH_PROJECT_SUCCESS,
    FINISH_PROJECT_FAILED,

    DELETE_PROJECT_SUCCESS,
    DELETE_PROJECT_FAILED
}
