const RESET_PROJECTS_ERRORS = "RESET_PROJECTS_ERRORS";

const FETCHING_PROJECTS = "FETCHING_PROJECTS";
const FETCHING_PROJECTS_SUCCESS = "FETCHING_PROJECTS_SUCCESS";
const FETCHING_PROJECTS_FAILED = "FETCHING_PROJECTS_FAILED";

export {
    RESET_PROJECTS_ERRORS,
    
    FETCHING_PROJECTS,
    FETCHING_PROJECTS_SUCCESS,
    FETCHING_PROJECTS_FAILED,


}
