export * from './Auth';
export * from './Home';
export * from './AddProject';
export * from './ProjectDetails';
export * from './Employees';
export * from './AddEmployeeScreen';
export * from './EditEmployeeScreen';
export * from './Dashboard';
export * from './Profile';
export * from './EditTask';
export * from './Materials';
// export * from './Calculations';
// export * from './Attendence';
export * from './EmployeeDetailsScreen';