export default {
    bg: '#EEEEEE',
    primary: '#326273',
    secondary: '#5C9EAD',
    lightBlue: '#98DAD9',
    appWhite: '#EAEBED',
    text: '#EAEBED',
    buttons: '#937666',
    white: '#fff',
    black: '#000',
    red: '#ff0000',

    // primary: '#2E424D',
    // secondary: '#5B8291',
    // lightBlue: '#98DAD9',
    // appWhite: '#EAEBED',
    // text: '#EAEBED',
    // buttons: '#EAEBED',
    // white: '#fff',
    // black: '#000',
    // red: '#ff0000',
}
